export const ROUTES = {
  ADMIN: '/admin',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_DRIVERS: '/admin/drivers',
  ADMIN_DRIVER_RIDE_DETAILS: '/admin/drivers/:id/rides/:rideId',
  ADMIN_DRIVER_APPROVALS: '/admin/drivers/approvals',
  ADMIN_DRIVER_APPROVAL_REVIEW: '/admin/drivers/approvals/:driverId',
  ADMIN_CUSTOMERS: '/admin/customers',
  ADMIN_CUSTOMER_DETAILS: '/admin/customers/:id',
  ADMIN_CUSTOMER_TRIPS: '/admin/customers/:id/trips',
  ADMIN_TRIPS: '/admin/trips',
  ADMIN_TRIP_DETAILS: '/admin/trips/:tripId',
  ADMIN_VEHICLES: '/admin/vehicles',
  ADMIN_VEHICLE_TYPES: '/admin/vehicles/types',
  ADMIN_VEHICLE_DETAILS: '/admin/vehicles/:vehicleId',
  ADMIN_PAYMENTS_TRANSACTIONS: '/admin/payments/transactions',
  ADMIN_PAYMENTS_DRIVER_EARNINGS: '/admin/payments/driver-earnings',
  ADMIN_PAYMENTS_REVENUE: '/admin/payments/revenue',
  ADMIN_PAYMENTS_PAYOUTS: '/admin/payments/payouts',
  ADMIN_OPERATIONAL_ZONES: '/admin/operational-zones',
  ADMIN_OPERATIONAL_ZONES_CREATE: '/admin/operational-zones/create',
  ADMIN_OPERATIONAL_ZONES_EDIT: '/admin/operational-zones/:id/edit',
  ADMIN_SUPPORT: '/admin/support',
} as const

export const UI_COLORS = {
  primary: '#FFC107',
  background: '#F8FAFC',
  cardBackground: '#FFFFFF',
  border: '#E5E7EB',
  textPrimary: '#111827',
  textSecondary: '#6B7280',
} as const
